name=MCP2515-nb
version=0.1.0
author=WitchCraftWorks Team, laszloh
maintainer=WitchCraftWorks Team, laszloh
sentence=Arduino library for MCP2515 with non-blocking support.
paragraph=Supports Microchip MCP2515 based boards/shields and non-blocking write operations.
category=Communication
url=https://github.com/laszloh/arduino-MCP2515-nb
architectures=*
includes=MCP2515.h
depends=Embedded Template Library ETL
